### ISSUE TITLE
LICENSE可以改吗

### ISSUE THREAD

**Issue by tcztzy** [liuyug/django-alipay#5]
GPL太残暴了，做这个支付开发的，多半都不会GPL吧。MIT或者BSD会比较好吧。。。

**Comment by liuyug** [comment]
残暴 这个词太过了。没有 GPL 哪有现在的 开源世界。

我已经更改 LICENSE 到 MIT。欢迎使用。

**Comment by tcztzy** [comment]
我知道措辞有点问题，道歉。谢谢更改LICENSE，我会多提pull request哒
