### ISSUE TITLE
[疑问] 是否实现了支付宝签名验证

### ISSUE THREAD

**Issue by qiwihui** [liuyug/django-alipay#7]
根据API中[支付宝服务器异步通知参数说明](https://doc.open.alipay.com/doc2/detail?treeId=59&articleId=103666&docType=1)的描述：

> 当支付宝处理完成后会把数据结果反馈给商户。 商户获得这些数据时，必须进行如下处理。
> 验证签名
> 首先必需验证签名，然后验证是否是支付宝发来的通知。
> 验证是否是支付宝发来的通知
> 请参见验证是否是支付宝发来的通知。
> ...

请问这个app里面是否有关于签名验证的地方呢？还是这个需要实现的时候自己验证？

**Comment by liuyug** [comment]
验证了签名 alipay/forms.py:    def clean_sign(self)

我忘记了为什么没有加入到 verify 函数中去的原因。你自己调试吧。
alipay/models.py:    def verify(self, item_check_callable=None):
alipay/create_partner_trade_by_buyer/ptn/views.py:        ptn_obj.verify(item_check_callable)
